(function () {
    function generateDoc() {
        var date = new Date(Date.now());
        var sender = document.getElementById('sender').value;
        var receiver = document.getElementById('receiver').value;
        var amount = document.getElementById('amount').value;

        var doc = "; requires signature of the debtor\n"
        doc += date.getFullYear() + "/" + date.getDate() + "/" + date.getDay() + " * transfer\n"
        doc += "    " + sender + ":Assets -" + amount + " guld\n"
        doc += "    " + sender + ":Expenses " + amount + " guld\n"
        doc += "    " + receiver + ":Assets " + amount + " guld\n"
        doc += "    " + receiver + ":Income -" + amount + " guld\n"

        return doc;
    }

    var generate = document.getElementById('generate');

    generate.addEventListener('click', function () {
        var email = 'sample@gmail.com';
        var subject = "Autogenerated transaction";
        var emailBody = generateDoc();
        document.location = "mailto:" + email + "?subject=" + subject + "&body=" + emailBody;
    }, false);

    // Start
    var guld_transfer = document.createElement("div");
    guld_transfer.id = "guld_transfer";
    guld_transfer.innerHTML = "htmldata";
    document.body.appendChild(guld_transfer);
    console.log("here");
})();